### ISSUE TITLE
run_vision_server command not found

### ISSUE THREAD

**Issue by ameyk1** [Dingry/bunny_teleop_server#1]
From Step 5: https://dingry.github.io/BunnyVisionPro/getstarted/usage/#5-start-server-nodes-inside-docker

When I run server, it gives me, command not found error:

run_vision_server command not found.

**Comment by yzqin** [comment]
Hi @ameyk1,

I apologize for the typo in the documentation you received, which has now been corrected in a recent commit. The error previously directed users to a base Docker image instead of our specified image `yzqin/bunny_teleop_server`.

To resolve this, please stop the incorrect Docker container with the following commands:

```shell
docker container stop bunny_teleop_server
docker container prune
```

Afterwards, re-run the code as outlined in the updated documentation. This should resolve the issue.

For any future concerns or issues related to this project, please feel free to open an issue in our main repository at `https://github.com/Dingry/BunnyVisionPro`. This will help us address your queries more promptly. 

I will close this issue. If you have further questions, you can open up a new issue in the main repo.

Regards,
Yuzhe
